Fix databricks-cli 0.17.6 urllib3 Retry.DEFAULT_METHOD_WHITELIST issue
Since urllib 2.0 was release, our main branch has been broken in the CI:
  File /Users/tati/Code/astro-provider-databricks/src/astro_databricks/operators/notebook.py, line 236, in _get_api_client
    return ApiClient(
  File /Users/tati/Code/astro-provider-databricks/.nox/test-3-10-airflow-2-5/lib/python3.10/site-packages/databricks_cli/sdk/api_client.py, line 106, in __init__
    method_whitelist=set({'POST'}) | set(Retry.DEFAULT_METHOD_WHITELIST),
AttributeError: type object 'Retry' has no attribute 'DEFAULT_METHOD_WHITELIST'

Until there is a new databricks-cli release with this fix:
https://github.com/databricks/databricks-cli/issues/634

We should pin the version of urllib, to avoid this error.