Passing: $ nox -s "test-3.8(airflow='2.5')" -- --ignore "tests/test_example_dags.py"
But not running the DAG itself, due to an issue with Metadata.
$ AIRFLOW_HOME=`pwd` airflow dags test example_databricks_workflow  `date -Iseconds`

```
   [2023-04-20 15:25:05,695] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/tati/Code/astro-provider-databricks/src/astro_databricks/operators/notebook.py", line 253, in execute
    databricks_metadata = DatabricksMetaData(**self.databricks_metadata)
TypeError: type object argument after ** must be a mapping, not NoneType
```

The template is being resolved as expected.